source ~/.config/nvim/vim/plugins.vim
source ~/.config/nvim/vim/functions.vim
source ~/.config/nvim/vim/config.vim
source ~/.config/nvim/vim/autocommands.vim
source ~/.config/nvim/vim/key_bindnings.vim
source ~/.config/nvim/vim/abbreviations.vim
source ~/.config/nvim/vim/python_autocommands.vim
source ~/.config/nvim/vim/js_autocommands.vim
source ~/.config/nvim/vim/java_autocommands.vim
source ~/.config/nvim/vim/cpp_c_autocommands.vim
source ~/.config/nvim/vim/cocc.vim
